import IMovieCard from "../../../types/IMovieCard";
import axios, {AxiosResponse} from "axios";

export const getSlides =async (): Promise<AxiosResponse>=>{
  return axios.get('http://85.237.34.125:4000/filter/films?genres=komediya&rating=7.5');
}

export const slides: IMovieCard[] = [
  {
    id: 1,
    imgUrl: "/images/film1.jpeg",
    route: "/",
    rating: "8,6",
    ratingBars: [40, 50, 60, 70],
    chartRating: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 2,
    imgUrl: "/images/film2.jpeg",
    route: "/",
    rating: "8,6",
    ratingBars: [40, 50, 60, 70],
    chartRating: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 3,
    imgUrl: "/images/film3.jpeg",
    route: "/",
    rating: "8,6",
    ratingBars: [40, 50, 60, 70],
    chartRating: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 4,
    imgUrl: "/images/film4.jpeg",
    route: "/",
    rating: "8,6",
    ratingBars: [40, 50, 60, 70],
    chartRating: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 5,
    imgUrl: "/images/film1.jpeg",
    route: "/",
    rating: "8,6",
    ratingBars: [40, 50, 60, 70],
    chartRating: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 6,
    imgUrl: "/images/film2.jpeg",
    route: "/",
    rating: "8,6",
    ratingBars: [40, 50, 60, 70],
    chartRating: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 7,
    imgUrl: "/images/film3.jpeg",
    route: "/",
    rating: "8,6",
    ratingBars: [40, 50, 60, 70],
    chartRating: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 8,
    imgUrl: "/images/film4.jpeg",
    route: "/",
    rating: "8,6",
    ratingBars: [40, 50, 60, 70],
    chartRating: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
];
