export const slides = [
  {
    id: 1,
    imgUrl: "/images/film1.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBars: [40, 50, 60, 70],
    chartRaiting: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 2,
    imgUrl: "/images/film2.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBars: [40, 50, 60, 70],
    chartRaiting: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 3,
    imgUrl: "/images/film3.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBars: [40, 50, 60, 70],
    chartRaiting: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 4,
    imgUrl: "/images/film4.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBars: [40, 50, 60, 70],
    chartRaiting: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 5,
    imgUrl: "/images/film1.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBars: [40, 50, 60, 70],
    chartRaiting: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 6,
    imgUrl: "/images/film2.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBars: [40, 50, 60, 70],
    chartRaiting: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 7,
    imgUrl: "/images/film3.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBars: [40, 50, 60, 70],
    chartRaiting: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 8,
    imgUrl: "/images/film4.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBars: [40, 50, 60, 70],
    chartRaiting: 40,
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
];
