export const slides = [
  {
    id: 1,
    imgUrl: "/images/film1.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBar1: "40%",
    raitingBar2: "40%",
    raitingBar3: "40%",
    raitingBar4: "40%",
    chartRaiting: "40%",
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 2,
    imgUrl: "/images/film2.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBar1: "40%",
    raitingBar2: "50%",
    raitingBar3: "40%",
    raitingBar4: "40%",
    chartRaiting: "60%",
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 3,
    imgUrl: "/images/film3.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBar1: "40%",
    raitingBar2: "50%",
    raitingBar3: "40%",
    raitingBar4: "50%",
    chartRaiting: "40%",
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 4,
    imgUrl: "/images/film4.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBar1: "50%",
    raitingBar2: "40%",
    raitingBar3: "50%",
    raitingBar4: "40%",
    chartRaiting: "40%",
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 5,
    imgUrl: "/images/film1.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBar1: "40%",
    raitingBar2: "40%",
    raitingBar3: "40%",
    raitingBar4: "40%",
    chartRaiting: "40%",
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 6,
    imgUrl: "/images/film2.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBar1: "40%",
    raitingBar2: "60%",
    raitingBar3: "40%",
    raitingBar4: "40%",
    chartRaiting: "60%",
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
  {
    id: 7,
    imgUrl: "/images/film3.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBar1: "40%",
    raitingBar2: "60%",
    raitingBar3: "40%",
    raitingBar4: "60%",
    chartRaiting: "40%",
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 1,
  },
  {
    id: 8,
    imgUrl: "/images/film4.jpeg",
    route: "/",
    raiting: "8,6",
    raitingBar1: "60%",
    raitingBar2: "40%",
    raitingBar3: "40%",
    raitingBar4: "60%",
    chartRaiting: "40%",
    chartName: "сюжет",
    info: "2016, США, Для детелй",
    infoTime: "90 минут",
    title: "Тень за спиной",
    type: 0,
  },
];
