import {ICreator} from "/src/types/ICreator";

export const creatorsData: ICreator[] = [
  {firstName: "Грег",      lastName: "Яйтанс",     role: "режиссёр"},
  {firstName: "Кэти",      lastName: "Джейкобс",   role: "режиссёр", imageUrl: "/images/creators/2.jpg"},
  {firstName: "Хью",       lastName: "Лори",       role: "актёр",    imageUrl: "/images/creators/3.jpg"},
  {firstName: "Роберт",    lastName: "Леонард",    role: "актёр",    imageUrl: "/images/creators/4.jpg"},
  {firstName: "Лиза",      lastName: "Эдельштейн", role: "актёр",    imageUrl: "/images/creators/5.jpg"},
  {firstName: "Омар",      lastName: "Эппс",       role: "актёр",    imageUrl: "/images/creators/6.jpg"},
  {firstName: "Джесси",    lastName: "Спенсер",    role: "актёр",    imageUrl: "/images/creators/7.jpg"},
  {firstName: "Дженнифер", lastName: "Моррисон",   role: "актёр",    imageUrl: "/images/creators/8.jpg"},
  {firstName: "Питер",     lastName: "Джекобсон",  role: "актёр",    imageUrl: "/images/creators/9.jpg"},
  {firstName: "Оливия",    lastName: "Уайлд",      role: "актёр",    imageUrl: "/images/creators/10.jpg"},
  {firstName: "Грег",      lastName: "Яйтанс",     role: "режиссёр"},
  {firstName: "Кэти",      lastName: "Джейкобс",   role: "режиссёр", imageUrl: "/images/creators/2.jpg"},
  {firstName: "Хью",       lastName: "Лори",       role: "актёр",    imageUrl: "/images/creators/3.jpg"},
  {firstName: "Роберт",    lastName: "Леонард",    role: "актёр",    imageUrl: "/images/creators/4.jpg"},
  {firstName: "Лиза",      lastName: "Эдельштейн", role: "актёр",    imageUrl: "/images/creators/5.jpg"},
  {firstName: "Хью",       lastName: "Лори",       role: "актёр",    imageUrl: "/images/creators/3.jpg"},
  {firstName: "Роберт",    lastName: "Леонард",    role: "актёр",    imageUrl: "/images/creators/4.jpg"},
  {firstName: "Лиза",      lastName: "Эдельштейн", role: "актёр",    imageUrl: "/images/creators/5.jpg"},
  {firstName: "Омар",      lastName: "Эппс",       role: "актёр",    imageUrl: "/images/creators/6.jpg"},
  {firstName: "Джесси",    lastName: "Спенсер",    role: "актёр",    imageUrl: "/images/creators/7.jpg"},
  {firstName: "Дженнифер", lastName: "Моррисон",   role: "актёр",    imageUrl: "/images/creators/8.jpg"},
  {firstName: "Питер",     lastName: "Джекобсон",  role: "актёр",    imageUrl: "/images/creators/9.jpg"},
  {firstName: "Оливия",    lastName: "Уайлд",      role: "актёр",    imageUrl: "/images/creators/10.jpg"},
]
